### ISSUE TITLE
Integration benchmarks of Ascertainment fail in certain combinations

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#357] opened 2024-07-10 09:22 UTC
In developing integration benchmarks I see the following issue when a Ascertainment model is passed to a LatentDelay and only where the latent model the ascertainment model uses contains random variables (i.e `FixedIntercept` does not trigger this). 

I think this is something to do with line 76 which is where a link field from `Ascertainment` is used but I think the actual issue is in the passing of the `Ascertainment` struct (?). This is low priority whilst we set up more infra but I think could point to a deeper issue.

```julia
using BenchmarkTools, TuringBenchmarking, EpiAware
suite = BenchmarkGroup()
suite["integration"] = BenchmarkGroup()

let
    using Distributions

    obs = LatentDelay(
        Ascertainment(
            NegativeBinomialError(), Intercept(Normal(0, 1)); link = x -> exp.(x)
        ),
        LogNormal(1.6, 0.2)
    )
    I_t = fill(100, 10)
    gen_obs = generate_observations(obs, I_t, I_t)
    suite["Integration"]["LatentDelay - Ascertainment"] = make_turing_suite(gen_obs; check = true)
end
ERROR: ArgumentError: type does not have a definite number of fields
Stacktrace:
  [1] fieldcount(t::Any)
    @ Base ./reflection.jl:885
  [2] #s21#100
    @ ~/.julia/packages/ReverseDiff/p1MzG/src/derivatives/broadcast.jl:27 [inlined]
  [3] var"#s21#100"(F::Any, ::Any, ::Any)
    @ ReverseDiff ./none:0
  [4] (::Core.GeneratedFunctionStub)(::UInt64, ::LineNumberNode, ::Any, ::Vararg{Any})
    @ Core ./boot.jl:602
  [5] istypeorclosure
    @ ~/.julia/packages/ReverseDiff/p1MzG/src/derivatives/broadcast.jl:21 [inlined]
  [6] mayhavetracked
    @ ~/.julia/packages/ReverseDiff/p1MzG/src/derivatives/broadcast.jl:29 [inlined]
  [7] _any_tuple
    @ ./reduce.jl:1241 [inlined]
  [8] any
    @ ./reduce.jl:1237 [inlined]
  [9] mayhavetracked
    @ ~/.julia/packages/ReverseDiff/p1MzG/src/derivatives/broadcast.jl:33 [inlined]
 [10] get_implementation
    @ ~/.julia/packages/ReverseDiff/p1MzG/src/derivatives/broadcast.jl:73 [inlined]
 [11] copy(_bc::Base.Broadcast.Broadcasted{ReverseDiff.TrackedStyle, Tuple{…}, typeof(*), Tuple{…}})
    @ ReverseDiff ~/.julia/packages/ReverseDiff/p1MzG/src/derivatives/broadcast.jl:92
 [12] materialize(bc::Base.Broadcast.Broadcasted{ReverseDiff.TrackedStyle, Nothing, typeof(*), Tuple{…}})
    @ Base.Broadcast ./broadcast.jl:903
 [13] generate_observations(__model__::Model{…}, __varinfo__::DynamicPPL.ThreadSafeVarInfo{…}, __context__::DefaultContext, obs_model::Ascertainment{…}, y_t::Vector{…}, Y_t::Vector{…})
    @ EpiAware.EpiObsModels ~/Dropbox/academic/projects/Rt-without-renewal/EpiAware/src/EpiObsModels/modifiers/ascertainment/Ascertainment.jl:76
```

**Comment by seabbs** [comment] 2024-07-17 20:37
@SamuelBrand1 reminder that this may be what you are seeing when using `LatentDelay`?

**Comment by SamuelBrand1** [comment] 2024-07-22 10:29
A MRE for a similar error in using `LatentDelay` that might be related.

Adding `ReverseDiff` to the test env

```julia
julia> using TestEnv
julia> TestEnv.activate()
(jl_eqwOsV) pkg> add ReverseDiff
```

Example that fails:

- Generate data from a combination of random walk for log incidence and pass to latent delays (with neg bin errors)
```julia
using EpiAware, Random, Turing, FillArrays, Distributions, LinearAlgebra, DynamicPPL
Random.seed!(1234)

latent_process = RandomWalk(init_prior = Normal(log(100.0), 0.25), std_prior = HalfNormal(1.))
obs_error_model = NegativeBinomialError(cluster_factor_prior = HalfNormal(0.05))
d_delay = Gamma(10, 5 / 10)
obs_model = LatentDelay(obs_error_model, d_delay)

@model function test_negbin_errors_with_delays(rw, obs, y_t)
        n = ismissing(y_t) ? 50 : length(y_t)
        @submodel Z_t = generate_latent(rw, n)
        @submodel gen_y_t = generate_observations(obs, y_t, exp.(Z_t))
        return exp.(Z_t), gen_y_t
end

gen_mdl = test_negbin_errors_with_delays(latent_process, obs_model, missing)
Z_t_obs, y_t_obs = gen_mdl()
```
- Run the inference which fails
```julia
mdl = test_negbin_errors_with_delays(latent_process, obs_model, y_t_obs)
ad = AutoReverseDiff(; compile = false)

chn = sample(mdl, NUTS(adtype = ad), 100, progess = true)
#ERROR: TypeError: in TrackedReal, in V, expected V<:Real, got Type{Union{Missing, Float64}}
```

- **NOTE**. I can change this so that the cases are all integers.

```julia
 y_t_obs_new = rand(80:120, 50)
mdl2 = test_negbin_errors_with_delays(latent_process, obs_model, y_t_obs_new)
ad = AutoReverseDiff(; compile = false)
chn2 = sample(mdl2, NUTS(adtype = ad), 100, progess = true)
#ERROR: TypeError: in TrackedReal, in V, expected V<:Real, got Type{Union{Missing, Float64}}
```

**Comment by SamuelBrand1** [comment] 2024-07-22 10:32
My first pass is that the problem is here, which creates an eltype of `Union{Missing, Float64}` in the array which seems to now be a problem with `ReverseDiff`. We can vary this but I think we want to be careful.

https://github.com/CDCgov/Rt-without-renewal/blob/cc8e0d20b9ece535f9b201d38f9aa1a85bc43bea/EpiAware/src/EpiObsModels/modifiers/LatentDelay.jl#L75

**Comment by seabbs** [comment] 2024-07-22 10:52
Does this still occur with the update to LatentDelay and if you remove LatentDelay entirely?

**Comment by SamuelBrand1** [comment] 2024-07-22 11:00
> Does this still occur with the update to LatentDelay and if you remove LatentDelay entirely? Its odd this usage fails entirely given other uses work? Do you think there is anything special about this implementation that is causing problems or are we just missing this common use case with our unit tests right now?

> Does this still occur with the update to LatentDelay

Yes, this is the just merged to main version of EpiAware.

> if you remove LatentDelay entirely?

It works without `LatentDelay` e.g. in the things already committed in #371 (although that seems to be erroring in CI but not locally and I need to investigate that).

> Do you think there is anything special about this implementation that is causing problems

I _think_ the way we are generating arrays with eltype `Union{Missing, <: Real}` is causing a problem for `ReverseDiff`. There are ways around that (obviously) by making `complete_obs` an array with only `<: Real` eltype and not using `missing` values to indicate time points where the observation is influenced by left truncation in the latent infections.

**Comment by seabbs** [comment] 2024-07-22 12:04
For example one difference is that here you calc n inside the @model call whilst everywhere else we do that outside and pass it in (i.e https://github.com/CDCgov/Rt-without-renewal/blob/cc8e0d20b9ece535f9b201d38f9aa1a85bc43bea/EpiAware/src/EpiAwareUtils/turing-methods.jl#L14)

**Comment by SamuelBrand1** [comment] 2024-07-22 12:10
> No sorry that isn't my question. My question is about the configuration you are using here vs coming via a EpiProblem formulation

I'm putting the configs together directly as per the example above

**Closed** 2024-07-23 17:04 UTC
Labels: bug, EpiAware
